### ISSUE TITLE
[Requests] BLM Fire IV changes into Flare Star when Astral Gauge is full

### ISSUE THREAD

**Issue by HPDeskJet2540** [MKhayle/XIVComboExpanded#273]
I think this will be a great additon without having to change the hotbar setup from EW while not causing any problem to the rotation

**Comment by MKhayle** [comment]
I will get a look at it when gauge data will be updated in Dalamud's ClientStruct!

**Comment by HPDeskJet2540** [comment]
> I will get a look at it when gauge data will be updated in Dalamud's ClientStruct!

Thank you! Really appericate your effort on this plugin. Do you pose a change log for the updates?

**Comment by MKhayle** [comment]
I do it in the commits, but aside from that, it's a bit tedious to manage because a LOT happens all the time but I started trying to list things here https://github.com/MKhayle/XIVComboExpanded/discussions/250

**Comment by HPDeskJet2540** [comment]
I see, I can see it is a lot of work, thank you for the reply!

**Comment by MKhayle** [comment]
![image](https://github.com/MKhayle/XIVComboExpanded/assets/4359469/eea5c20b-f666-4d91-bf24-0951044c8e54)

https://github.com/MKhayle/XIVComboExpanded/commit/eef45e24e0329831cb47bf080c4d466cc5c16bdb 1.5.0.37 should add an option for this

**Comment by HPDeskJet2540** [comment]
Hello, I think it broke the Enochain Feature (Fire 4 and Blizzard 4)

**Comment by MKhayle** [comment]
oh god yes, it probably returns Flare?

**Comment by HPDeskJet2540** [comment]
I think everything under Black Mage broke

**Comment by MKhayle** [comment]
I pushed a fix, forgot to remove a line, should be good now

**Comment by MKhayle** [comment]
https://github.com/MKhayle/XIVComboExpanded/commit/1cbda1cb33df7c01f1db7eef60c18a3a8920bed2 1.5.0.38

**Comment by MKhayle** [comment]
(I can't test it myself as it requires being lvl 100)

**Comment by HPDeskJet2540** [comment]
Everythin under Black Mage is still broken.
In addition perhaps change Flare into Astral Soul when gauge is full as well? Of course merely a suggestion whenever you have time.

**Comment by MKhayle** [comment]
Can you show me or explain precisely what you mean by "broken" so that I can understand better the issue?

**Comment by HPDeskJet2540** [comment]
So not single one of the options under black mage is working right now, not just Enochain feaure, everything black mage related

**Comment by MKhayle** [comment]
Ah, I know what's going on. 
That's because it's using the new gauge which only is available in staging dalamud.
Type `/xlbranch` and pick the `staging` version, and then restart. If you're afraid of any issues with a testing version, you can also wait 1-2 days until `release` gets the gauge update.

**Comment by HPDeskJet2540** [comment]
thank you, I will wait until release and report back if there is any issue!

**Comment by MKhayle** [comment]
Sorry for the inconvenience!
